export const STORAGE_TOKEN_KEY = 'Access-Token'
export const STORAGE_LANG_KEY = 'app_lang'
export const HISTORY_ACCOUNT = 'history_account'
export const HISTORY_PASSWORD = 'history_password'
export const SAVE_PASSWORD = 'save_password'
