/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'login': RouteRecordInfo<'login', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/home/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/home/counter', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/home/keepalive', Record<never, never>, Record<never, never>>,
    'menu': RouteRecordInfo<'menu', '/home/menu', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/home/mock', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/home/unocss', Record<never, never>, Record<never, never>>,
    'video': RouteRecordInfo<'video', '/home/video', Record<never, never>, Record<never, never>>,
    'videoInfo': RouteRecordInfo<'videoInfo', '/home/video/info', Record<never, never>, Record<never, never>>,
    'search': RouteRecordInfo<'search', '/home/video/search', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'edit': RouteRecordInfo<'edit', '/profile/edit', Record<never, never>, Record<never, never>>,
    'history': RouteRecordInfo<'history', '/profile/history', Record<never, never>, Record<never, never>>,
    'collector': RouteRecordInfo<'collector', '/profile/star', Record<never, never>, Record<never, never>>,
  }
}
